arches:
  - x86_64
contentOrigin:
  repofiles:
    - ubi.repo
stages:
- image: brew.registry.redhat.io/rh-osbs/openshift-golang-builder:v1.24@sha256:021ab8e6e4af3d1683b52ec985996f9421edb2111dc697b5781dee3c7595ae00
packages:
  - gcc
  - gcc-c++
  - libstdc++
  - libstdc++-devel
  - cmake
  - clang
context:
  containerfile: Dockerfile.konflux
